import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import "./globals.css";
import SplashLayout from "./SplashLayout";

const encodeSans = Encode_Sans({
  variable: "--font-encode_Sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tiaki Taonga Trust",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${encodeSans.variable} antialiased`}>
        <SplashLayout>{children}</SplashLayout>
      </body>
    </html>
  );
}
