import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import OpeningHome from "./components/opening-home/OpeningHome";

const encodeSans = Encode_Sans({
  variable: "--font-encode_Sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${encodeSans.variable} ${encodeSans.variable} antialiased`}
      >
        <OpeningHome />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
